config/routes.rb
Rails.application.routes.draw do
  resources :product,only: [:new,:create,:destroy]
  resources :cartitem,only: [:create,:destroy]
  
  get 'cart/show'
  root 'top#main'
  get 'top/main'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
    has_many :caritem,dependent: :destroy
end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
    
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
    
    belongs_to :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cartitems = Cartitem.where(cart_id: session[:cart_id])
    @tal = 0 
  end
end

app/controllers/cartitem_controller.rb
class CartitemController < ApplicationController
  def create
    logger.debug "ID:"
    logger.debug params[:id]
    cartitem = Cartitem.find_by(product_id: params[:id],cart_id: session[:cart_id])
    if cartitem
      cartitem.qty += 1
    else
      cartitem = Cartitem.new(qty:1,product_id: params[:id], cart_id: session[:cart_id])
    end
    cartitem.save
    redirect_to cart_show_path
  end

  def destroy
    Cartitem.find(params[:id]).destroy
    redirect_to cart_show_path
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(name: params[:product][:name],price: params[:product][:price])
    @product.save
    redirect_to top_main_path
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to top_main_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    unless session[:cart_id]
      cart = Cart.create
      session[:cart_id] = cart.id
    end
    
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cartitem_helper.rb
module CartitemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart/show.html.erb
<table border="1">
    カートの中
    
<tr>
    <th>商品名</th>
    <th>価格</th>
    <th>数量</th>
    <th>削除</th>
</tr>
    
    <% @cartitems.each do |c| %>
      <% p=Product.find(c.product_id) %>
      <% @tal += p.price * c.qty %>
      <tr>
          <td><%= p.name %></td>
          <td><%= p.price %></td>
          <td><%= c.qty %></td>
          <td><%=link_to "削除",cartitem_path(c),method: :delete, data: {confirm: "削除していいですか？"} %></td>
      </tr>
    <% end %>
</table>

<p>
    合計金額：<%= @tal %>円 
</p>

<br>
<%= link_to "戻る",top_main_path %>

app/views/cartitem/create.html.erb
<h1>Cartitem#create</h1>
<p>Find me in app/views/cartitem/create.html.erb</p>

app/views/cartitem/destroy.html.erb
<h1>Cartitem#destroy</h1>
<p>Find me in app/views/cartitem/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/product/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/product/new.html.erb
<%= form_for @product,:url => {:action => :create} do |f| %>

  <%= f.label :name,"商品名" %>
  <%= f.text_field :name %><br>
  
  <%= f.label :price,"値段(円)" %>
  <%= f.text_field :price %><br>
  
  <%= f.submit "登録" %>

<% end %>
<%= link_to "戻る",top_main_path %>

app/views/top/main.html.erb
<table border="1">

商品一覧


<tr>
    <th>商品名</th>
    <th>価格</th>
    <th>カートに入れる</th>
    <th>削除</th>
</tr>

<% @products.each do |p| %>
  
  <tr>
      <td><%= p.name %></td>
      <td><%= p.price %></td>
      <td><%= link_to "カートに入れる",cartitem_index_path(id: p.id),method: :post %></td>
      <td><%= link_to "削除",product_path(p),method: :delete,data: {confirm: '削除していいですか？' } %></td>
  </tr>
  
<% end %>

</table>

<p>
    <%= link_to "カートを見る",cart_show_path %>
</p>

<p>
    <%= link_to "商品登録",new_product_path %>
</p>